import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  static const String _langKey = 'selected_language';
  Locale _currentLocale = const Locale('en');

  Locale get currentLocale => _currentLocale;

  LanguageProvider();

  Future<void> loadSettings() async {
    final prefs = await SharedPreferences.getInstance();
    final langCode = prefs.getString(_langKey) ?? 'en';
    _currentLocale = Locale(langCode);
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) async {
    _currentLocale = Locale(languageCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_langKey, languageCode);
    notifyListeners();
  }

  // Simple translation helper
  String translate(String key) {
    return _translations[_currentLocale.languageCode]?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'Secure Stego',
      'send_secret': 'Send Secret',
      'reveal_secret': 'Reveal Secret',
      'contacts': 'Contacts',
      'history': 'History',
      'my_qr': 'My QR',
      'help': 'Help',
      'settings': 'Settings',
      'profile': 'Profile',
      'language': 'Language',
      'english': 'English',
      'amharic': 'Amharic',
      'welcome': 'Welcome back,',
      'tagline': 'Secure Messaging',
      'no_messages': 'No messages yet',
      'secured_with': 'Your messages are secured with RSA-2048',
      'encrypted_channel': 'Secure Channel',
      'e2e_encrypted': 'End-to-end encrypted',
      'type_message': 'Type a secret message...',
      'decode_success': 'Message Decoded successfully!',
      'decode_failed': 'No message here',
      'sent': 'Sent',
      'received': 'Received',
      'encrypted_data': 'Encrypted Data',
      'how_to_use': 'How to use',
      'got_it': 'GOT IT',
      'select_image_first': 'Please select an image first.',
      'enter_secret_message': 'Please enter a secret message.',
      'message_hidden': 'Message Hidden!',
      'hidden_action_prompt': 'What would you like to do with the encrypted image?',
      'save_to_gallery': 'SAVE TO GALLERY',
      'share': 'SHARE',
      'saved_to_gallery': 'Saved to Gallery',
      'operation_failed': 'Operation failed',
      'type_secret_hint': 'Secret message...',
      'clear_history': 'Clear History?',
      'clear_confirm': 'This will permanently delete all message logs from this device.',
      'cancel': 'Cancel',
      'clear_all': 'Clear All',
      'encryption_settings': 'Encryption Settings',
      'notifications': 'Notifications',
      'logout': 'Logout',
      'extract': 'Extract',
      'details': 'Details',
      'send_secret_sub': 'Encrypt and hide text within an image',
      'reveal_secret_sub': 'Extract hidden data from a stego-image',
      'quick_actions': 'QUICK ACTIONS',
      'help_step_1': '1. Sharing Public Keys',
      'help_desc_1': 'Go to \'Profile\' or \'My QR\' to share your public key with others. They need it to send you secrets.',
      'help_step_2': '2. Sending Secrets',
      'help_desc_2': 'Select \'Send Secret\', pick an image, enter your message, and select a contact.',
      'help_step_3': '3. IMPORTANT: Avoid Compression',
      'help_desc_3': 'When sending the stego-image via apps like Telegram or WhatsApp, you MUST send it as a \'FILE\' or \'DOCUMENT\'.',
      'help_desc_3_warn': 'If you send it as a \'Photo\', the app will compress it, which destroys the hidden message.',
      'select_recipient': 'Select Recipient',
      'add_contact_manual': 'Add Contact Manually',
      'contact_name': 'Contact Name',
      'public_key': 'Public Key',
      'paste_public_key': 'Paste the Base64 public key here',
      'add_select': 'ADD & SELECT',
      'select_contact_info': 'Select a contact to encrypt your message with their public key.',
      'no_contacts': 'No contacts found',
      'scan_qr_prompt': 'Scan a public key QR to add a contact',
      'scan_qr_code': 'SCAN QR CODE',
      'scan_qr': 'Scan QR',
      'enter_manually': 'ENTER MANUALLY',
      'scan_new': 'Scan New',
      'fingerprint': 'Fingerprint',
      'use_biometrics': 'Use Biometrics',
      'biometric_reason': 'Please authenticate to access your secure messages',
      'biometric_failed': 'Authentication failed',
      'enable_biometrics': 'Enable Biometric Authentication',
      'wipe_data': 'Wipe All Data',
      'wipe_data_confirm': 'Are you sure you want to delete all messages, contacts, and account data? This cannot be undone.',
      'wipe_all': 'WIPE EVERYTHING',
      'security_question': 'Security Question',
      'security_answer': 'Security Answer',
      'security_recovery': 'Security Recovery',
      'find_account': 'FIND ACCOUNT',
      'find_account_prompt': 'Enter your username to find your account.',
      'account_recovery': 'Account Recovery',
      'verify_answer': 'VERIFY ANSWER',
      'user_not_found': 'Username not found',
      'username_not_found': 'Username not found',
      'no_security_question': 'No security question set.',
      'pass_requirement': 'Password does not meet requirements',
      'passwords_mismatch': 'Passwords do not match',
      'password_reset_success': 'Password reset successful!',
      'set_new_password_prompt': 'Answer verified! Set your new password.',
      'confirm_new_password': 'Confirm New Password',
      'new_password': 'New Password',
      'change_password': 'Change Password',
      'password_changed': 'Password changed successfully',
      'auth_failed': 'Authentication failed',
      'incorrect_answer': 'Incorrect answer',
      'answer_verified': 'Answer verified! Set your new password.',
      'forgot_password': 'Forgot Password?',
      'no_account': "Don't have an account?",
      'login': 'SIGN IN',
      'register': 'Register',
      'fill_all_fields': 'Please fill all fields',
      'invalid_credentials': 'Wrong username or password',
      'no_registered_account': 'No registered account found',
      'password': 'Password',
      'encryption_info_title': 'End-to-End Encryption',
      'encryption_info_body': 'All messages are encrypted using RSA-2048. Only the recipient with the corresponding private key can decrypt and read your messages. The secret is hidden inside the image pixels using LSB steganography.',
      'notifications_settings': 'Notification Settings',
      'push_notifications': 'Push Notifications',
      'notify_on_receive': 'Notify when a new message is received',
      'grant_permissions': 'Grant Permissions',
      'permissions_desc': 'The app needs Camera and Storage access to function properly.',
      'camera_permission': 'Camera Permission',
      'storage_permission': 'Storage Permission',
      'grant_all': 'GRANT ALL PERMISSIONS',
      'permissions_granted': 'Permissions Granted!',
      'theme_mode': 'Theme Mode',
      'choose_theme': 'Choose Theme',
      'public_identity': 'Public Identity',
      'username': 'Username',
      'full_name': 'Full Name',
      'profile_updated': 'Profile updated',
      'not_logged_in': 'Not logged in',
      'security_info': 'Security Information',
      'your_public_key': 'Your Public Key',
      'loading_key': 'Loading key...',
      'show_qr_code': 'Show QR Code',
      'share_key_info': 'Share this key with others to receive encrypted messages.',
      'copy': 'Copy',
      'copied_to_clipboard': 'Copied to clipboard',
    },
    'am': {
      'app_title': 'ደህንነቱ የተጠበቀ ምስጢር',
      'send_secret': 'ምስጢር ላክ',
      'reveal_secret': 'ምስጢር ግለጽ',
      'contacts': 'እውቂያዎች',
      'history': 'ታሪክ',
      'my_qr': 'የእኔ QR',
      'help': 'እርዳታ',
      'settings': 'ቅንብሮች',
      'profile': 'መገለጫ',
      'language': 'ቋንቋ',
      'english': 'እንግሊዝኛ',
      'amharic': 'አማርኛ',
      'welcome': 'እንኳን ደህና መጡ፣',
      'tagline': 'ደህንነቱ የተጠበቀ መልዕክት',
      'no_messages': 'ምንም መልዕክቶች የሉም',
      'secured_with': 'መልእክቶችዎ በRSA-2048 የተጠበቁ ናቸው',
      'encrypted_channel': 'ደህንነቱ የተጠበቀ ቻናል',
      'e2e_encrypted': 'ከጫፍ እስከ ጫፍ የተመሰጠረ',
      'type_message': 'ምስጢራዊ መልዕክት ይተይቡ...',
      'decode_success': 'መልዕክቱ በተሳካ ሁኔታ ተገልጧል!',
      'decode_failed': 'ምንም መልዕክት የለም',
      'sent': 'የተላከ',
      'received': 'የደረሰ',
      'encrypted_data': 'የተመሰጠረ መረጃ',
      'how_to_use': 'እንዴት መጠቀም እንደሚቻል',
      'got_it': 'ገባኝ',
      'select_image_first': 'እባክዎ መጀመሪያ ምስል ይምረጡ።',
      'enter_secret_message': 'እባክዎ ምስጢራዊ መልዕክት ያስገቡ።',
      'message_hidden': 'መልዕክቱ ተደብቋል!',
      'hidden_action_prompt': 'ከተመሰጠረው ምስል ጋር ምን ማድረግ ይፈልጋሉ?',
      'save_to_gallery': 'በጋለሪ ውስጥ አስቀምጥ',
      'share': 'አጋራ',
      'saved_to_gallery': 'በጋለሪ ውስጥ ተቀምጧል',
      'operation_failed': 'ክዋኔው አልተሳካም',
      'type_secret_hint': 'ምስጢራዊ መልዕክት...',
      'clear_history': 'ታሪክን አጽዳ?',
      'clear_confirm': 'ይህ ሁሉንም የመልዕክት ምዝግብ ማስታዋሻዎች ከዚህ መሣሪያ ላይ በቋሚነት ይሰርዛል።',
      'cancel': 'ሰርዝ',
      'clear_all': 'ሁሉንም አጽዳ',
      'encryption_settings': 'የምስጠራ ቅንብሮች',
      'notifications': 'ማሳወቂያዎች',
      'logout': 'ውጣ',
      'extract': 'አውጣ',
      'details': 'ዝርዝሮች',
      'send_secret_sub': 'በምስል ውስጥ ጽሑፍን ደብቅ እና ምስጢር አድርግ',
      'reveal_secret_sub': 'ከምስል ውስጥ የተደበቀ መረጃን አውጣ',
      'quick_actions': 'ፈጣን እርምጃዎች',
      'help_step_1': '1. የህዝብ ቁልፎችን ማጋራት',
      'help_desc_1': 'የህዝብ ቁልፍዎን ለሌሎች ለማጋራት ወደ \'መገለጫ\' ወይም \'የእኔ QR\' ይሂዱ። ምስጢሮችን ለመላክ የእርስዎ ቁልፍ ያስፈልጋቸዋል።',
      'help_step_2': '2. ምስጢሮችን መላክ',
      'help_desc_2': '\'ምስጢር ላክ\' የሚለውን ይምረጡ፣ ምስል ይምረጡ፣ መልዕክትዎን ያስገቡ እና እውቂያ ይምረጡ።',
      'help_step_3': '3. አስፈላጊ፡ መጨናነቅን ያስወግዱ',
      'help_desc_3': 'ምስሉን በቴሌግራም ወይም በዋትስአፕ በኩል ሲልኩ እንደ \'FILE\' ወይም \'DOCUMENT\' መላክ አለብዎት።',
      'help_desc_3_warn': 'እንደ \'Photo\' ከላኩት አፑ ያሳንሰዋል (Compress ያደርገዋል)፣ ይህም የተደበቀውን መልዕክት ያጠፋዋል።',
      'select_recipient': 'ተቀባዩን ይምረጡ',
      'add_contact_manual': 'እውቂያን በእጅ ያክሉ',
      'contact_name': 'የእውቂያ ስም',
      'public_key': 'የህዝብ ቁልፍ',
      'paste_public_key': 'የBase64 የህዝብ ቁልፍ እዚህ ይለጥፉ',
      'add_select': 'አክል እና ምረጥ',
      'select_contact_info': 'መልዕክትዎን በህዝብ ቁልፍ ለመመስጠር እውቂያ ይምረጡ።',
      'no_contacts': 'ምንም እውቂያዎች አልተገኙም',
      'scan_qr_prompt': 'እውቂያ ለማከል የህዝብ ቁልፍ QR ይቃኙ',
      'scan_qr_code': 'QR ኮድ ይቃኙ',
      'scan_qr': 'QR ይቃኙ',
      'enter_manually': 'በእጅ ያስገቡ',
      'scan_new': 'አዲስ ይቃኙ',
      'fingerprint': 'ፊንገር ፕሪንት',
      'use_biometrics': 'ባዮሜትሪክስ ይጠቀሙ',
      'username': 'የተጠቃሚ ስም',
      'full_name': 'ሙሉ ስም',
      'profile_updated': 'መገለጫ ተዘምኗል',
      'not_logged_in': 'አልገቡም',
      'security_info': 'የደህንነት መረጃ',
      'your_public_key': 'የእርስዎ የህዝብ ቁልፍ',
      'loading_key': 'ቁልፎችን በመጫን ላይ...',
      'show_qr_code': 'QR ኮድ አሳይ',
      'share_key_info': 'የተመሰጠሩ መልዕክቶችን ለመቀበል ይህንን ቁልፍ ለሌሎች ያጋሩ።',
      'wipe_data': 'ሁሉንም መረጃ አጥፋ',
      'wipe_data_confirm': 'ሁሉንም መልዕክቶች፣ እውቂያዎች እና የመለያ መረጃዎችን መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት? ይህ ሊቀለበስ አይችልም።',
      'wipe_all': 'ሁሉንም አጥፋ',
      'security_question': 'የደህንነት ጥያቄ',
      'security_answer': 'የእርስዎ መልስ',
      'security_recovery': 'መለያን መልሶ ማግኘት',
      'find_account': 'መለያ ፈልግ',
      'find_account_prompt': 'መለያዎን ለማግኘት የተጠቃሚ ስምዎን ያስገቡ።',
      'account_recovery': 'መለያን መልሶ ማግኘት',
      'verify_answer': 'መልሱን አረጋግጥ',
      'user_not_found': 'ተጠቃሚው አልተገኘም',
      'username_not_found': 'ተጠቃሚው አልተገኘም',
      'no_security_question': 'የደህንነት ጥያቄ አልተዘጋጀም።',
      'pass_requirement': 'የይለፍ ቃሉ መስፈርቱን አያሟላም',
      'passwords_mismatch': 'የይለፍ ቃላቱ አይዛመዱም',
      'password_reset_success': 'የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯል!',
      'set_new_password_prompt': 'መልሱ ተረጋግጧል! አዲስ የይለፍ ቃል ያስገቡ።',
      'confirm_new_password': 'አዲሱን የይለፍ ቃል ያረጋግጡ',
      'new_password': 'አዲስ የይለፍ ቃል',
      'change_password': 'የይለፍ ቃል ቀይር',
      'password_changed': 'የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯል',
      'auth_failed': 'ማረጋገጥ አልተሳካም',
      'incorrect_answer': 'የተሳሳተ መልስ',
      'answer_verified': 'መልሱ ተረጋግጧል! አዲስ የይለፍ ቃል ያስገቡ።',
      'forgot_password': 'የይለፍ ቃል ረሱ?',
      'no_account': 'መለያ የለዎትም?',
      'login': 'ግባ',
      'register': 'ይመዝገቡ',
      'fill_all_fields': 'እባክዎ ሁሉንም መስኮች ይሙሉ',
      'invalid_credentials': 'የተሳሳተ የተጠቃሚ ስም ወይም የይለፍ ቃል',
      'no_registered_account': 'ምንም የተመዘገበ መለያ አልተገኘም',
      'password': 'የይለፍ ቃል',
      'encryption_info_title': 'ከጫፍ እስከ ጫፍ ምስጠራ',
      'encryption_info_body': 'ሁሉም መልዕክቶች በRSA-2048 በመጠቀም የተመሰጠሩ ናቸው። ተዛማጅ የግል ቁልፍ ያለው ተቀባይ ብቻ መልዕክቶችዎን መፍታት እና ማንበብ ይችላል። ምስጢሩ በLSB ስቴጋኖግራፊ በመጠቀም በምስል ፒክስሎች ውስጥ ተደብቋል።',
      'notifications_settings': 'የማሳወቂያ ቅንብሮች',
      'push_notifications': 'የግፋ ማሳወቂያዎች',
      'notify_on_receive': 'አዲስ መልዕክት ሲደርስ አሳውቅ',
      'grant_permissions': 'ፈቃዶችን ስጥ',
      'permissions_desc': 'አፕሊኬሽኑ በትክክል ለመስራት የካሜራ እና የማከማቻ መዳረሻ ያስፈልገዋል።',
      'camera_permission': 'የካሜራ ፈቃድ',
      'storage_permission': 'የማከማቻ ፈቃድ',
      'grant_all': 'ሁሉንም ፈቃዶች ስጥ',
      'permissions_granted': 'ፈቃዶች ተሰጥተዋል!',
      'theme_mode': 'ገጽታ',
      'choose_theme': 'ገጽታ ይምረጡ',
      'public_identity': 'ይፋዊ መለያ',
      'copy': 'ቅዳ',
      'copied_to_clipboard': 'ወደ ክሊፕቦርድ ተገልብጧል',
    }
  };
}
